$('table:first').remove();
$('table:eq(0)').remove();
// $('table:first:nth-child(1)').remove();
// $('table:eq(1)').remove();
// $('table').contents().unwrap();
// $('tr').contents().unwrap();
// $('td').contents().unwrap();
// $('tbody').contents().unwrap();
// $('font').contents().unwrap();
// $('b').contents().unwrap();
$('body').addClass('container');
$('*').css('background', '#F5F5F5');
$('*').css('color', '#616161');
$('.container').prepend("<div id='VTopEasy'> V-TOP Easy</div>");
// $('*').find('img[src="images/vit_logo6.jpg"]').remove();
$('*').find('img[src="images/vit_logo6.jpg"]').remove();
//$("[attribute=value]").remove();
// $("tr:has(img[attribute=value])").remove();
$('p').addClass('flow-text');
// $(":empty:not(:input)").remove();
$(".submit3").addClass("btn");
// $('table:first').text("");
// $('table').eq(1).remove();